/* This file was autogenerated by openCONFIGURATOR-1.4.1 on 26-Apr-2020 12:37:43 */
#ifndef XAP_h
#define XAP_h

#define COEF_FLOAT_POINT 10000

# define COMPUTED_PI_OUT_SIZE 16
typedef struct
{
	int64_t cmdvel_lwheel;
	int64_t cmdvel_rwheel;
} PI_OUT;

# define COMPUTED_PI_IN_SIZE 72
typedef struct
{
	int64_t mm_x_pos;
	int64_t mm_y_pos;
	int64_t mm_z_pos;
	int64_t mm_x_orient;
	int64_t mm_y_orient;
	int64_t mm_z_orient;
	int64_t mm_w_orient;
	int64_t odom_lwheel;
	int64_t odom_rwheel;
} PI_IN;

#endif
