/*
* This file was autogenerated by openCONFIGURATOR-2.2.1_release on 13-May-2020 00:04:55
* Project: epl4
* Application process for MN(240)
*/
#ifndef XAP_h
#define XAP_h

#define COMPUTED_PI_OUT_SIZE 72
typedef struct
{
	INT64 CN1_mm_x_pos1:64;
	INT64 CN1_mm_y_pos2:64;
	INT64 CN1_mm_z_pos3:64;
	INT64 CN1_mm_x_orient4:64;
	INT64 CN1_mm_y_orient5:64;
	INT64 CN1_mm_z_orient6:64;
	INT64 CN1_mm_w_orient7:64;
	INT64 CN1_odom_lwheel14:64;
	INT64 CN1_odom_rwheel15:64;
} PI_OUT;

#define COMPUTED_PI_IN_SIZE 16
typedef struct
{
	INT64 CN1_cmdvel_lwheel1:64;
	INT64 CN1_cmdvel_rwheel2:64;
} PI_IN;

#endif
