// Generated by gencpp from file rosepl_wrapper_mn/SdoTransfer.msg
// DO NOT EDIT!


#ifndef ROSEPL_WRAPPER_MN_MESSAGE_SDOTRANSFER_H
#define ROSEPL_WRAPPER_MN_MESSAGE_SDOTRANSFER_H

#include <ros/service_traits.h>


#include <rosepl_wrapper_mn/SdoTransferRequest.h>
#include <rosepl_wrapper_mn/SdoTransferResponse.h>


namespace rosepl_wrapper_mn
{

struct SdoTransfer
{

typedef SdoTransferRequest Request;
typedef SdoTransferResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SdoTransfer
} // namespace rosepl_wrapper_mn


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rosepl_wrapper_mn::SdoTransfer > {
  static const char* value()
  {
    return "7e21ae9a3de205dc320e50907fc35cdc";
  }

  static const char* value(const ::rosepl_wrapper_mn::SdoTransfer&) { return value(); }
};

template<>
struct DataType< ::rosepl_wrapper_mn::SdoTransfer > {
  static const char* value()
  {
    return "rosepl_wrapper_mn/SdoTransfer";
  }

  static const char* value(const ::rosepl_wrapper_mn::SdoTransfer&) { return value(); }
};


// service_traits::MD5Sum< ::rosepl_wrapper_mn::SdoTransferRequest> should match
// service_traits::MD5Sum< ::rosepl_wrapper_mn::SdoTransfer >
template<>
struct MD5Sum< ::rosepl_wrapper_mn::SdoTransferRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rosepl_wrapper_mn::SdoTransfer >::value();
  }
  static const char* value(const ::rosepl_wrapper_mn::SdoTransferRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosepl_wrapper_mn::SdoTransferRequest> should match
// service_traits::DataType< ::rosepl_wrapper_mn::SdoTransfer >
template<>
struct DataType< ::rosepl_wrapper_mn::SdoTransferRequest>
{
  static const char* value()
  {
    return DataType< ::rosepl_wrapper_mn::SdoTransfer >::value();
  }
  static const char* value(const ::rosepl_wrapper_mn::SdoTransferRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rosepl_wrapper_mn::SdoTransferResponse> should match
// service_traits::MD5Sum< ::rosepl_wrapper_mn::SdoTransfer >
template<>
struct MD5Sum< ::rosepl_wrapper_mn::SdoTransferResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rosepl_wrapper_mn::SdoTransfer >::value();
  }
  static const char* value(const ::rosepl_wrapper_mn::SdoTransferResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosepl_wrapper_mn::SdoTransferResponse> should match
// service_traits::DataType< ::rosepl_wrapper_mn::SdoTransfer >
template<>
struct DataType< ::rosepl_wrapper_mn::SdoTransferResponse>
{
  static const char* value()
  {
    return DataType< ::rosepl_wrapper_mn::SdoTransfer >::value();
  }
  static const char* value(const ::rosepl_wrapper_mn::SdoTransferResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSEPL_WRAPPER_MN_MESSAGE_SDOTRANSFER_H
