// Generated by gencpp from file rosepl_wrapper_mn/SignalSyncRequest.msg
// DO NOT EDIT!


#ifndef ROSEPL_WRAPPER_MN_MESSAGE_SIGNALSYNCREQUEST_H
#define ROSEPL_WRAPPER_MN_MESSAGE_SIGNALSYNCREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rosepl_wrapper_mn
{
template <class ContainerAllocator>
struct SignalSyncRequest_
{
  typedef SignalSyncRequest_<ContainerAllocator> Type;

  SignalSyncRequest_()
    : do_add(false)
    , pid(0)  {
    }
  SignalSyncRequest_(const ContainerAllocator& _alloc)
    : do_add(false)
    , pid(0)  {
  (void)_alloc;
    }



   typedef uint8_t _do_add_type;
  _do_add_type do_add;

   typedef uint16_t _pid_type;
  _pid_type pid;





  typedef boost::shared_ptr< ::rosepl_wrapper_mn::SignalSyncRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosepl_wrapper_mn::SignalSyncRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SignalSyncRequest_

typedef ::rosepl_wrapper_mn::SignalSyncRequest_<std::allocator<void> > SignalSyncRequest;

typedef boost::shared_ptr< ::rosepl_wrapper_mn::SignalSyncRequest > SignalSyncRequestPtr;
typedef boost::shared_ptr< ::rosepl_wrapper_mn::SignalSyncRequest const> SignalSyncRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosepl_wrapper_mn::SignalSyncRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosepl_wrapper_mn::SignalSyncRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rosepl_wrapper_mn::SignalSyncRequest_<ContainerAllocator1> & lhs, const ::rosepl_wrapper_mn::SignalSyncRequest_<ContainerAllocator2> & rhs)
{
  return lhs.do_add == rhs.do_add &&
    lhs.pid == rhs.pid;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rosepl_wrapper_mn::SignalSyncRequest_<ContainerAllocator1> & lhs, const ::rosepl_wrapper_mn::SignalSyncRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rosepl_wrapper_mn

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rosepl_wrapper_mn::SignalSyncRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosepl_wrapper_mn::SignalSyncRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosepl_wrapper_mn::SignalSyncRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosepl_wrapper_mn::SignalSyncRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosepl_wrapper_mn::SignalSyncRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosepl_wrapper_mn::SignalSyncRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosepl_wrapper_mn::SignalSyncRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "25337467ea805b76a9afc686a835191f";
  }

  static const char* value(const ::rosepl_wrapper_mn::SignalSyncRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x25337467ea805b76ULL;
  static const uint64_t static_value2 = 0xa9afc686a835191fULL;
};

template<class ContainerAllocator>
struct DataType< ::rosepl_wrapper_mn::SignalSyncRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosepl_wrapper_mn/SignalSyncRequest";
  }

  static const char* value(const ::rosepl_wrapper_mn::SignalSyncRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosepl_wrapper_mn::SignalSyncRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool do_add\n"
"uint16 pid\n"
;
  }

  static const char* value(const ::rosepl_wrapper_mn::SignalSyncRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosepl_wrapper_mn::SignalSyncRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.do_add);
      stream.next(m.pid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SignalSyncRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosepl_wrapper_mn::SignalSyncRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosepl_wrapper_mn::SignalSyncRequest_<ContainerAllocator>& v)
  {
    s << indent << "do_add: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.do_add);
    s << indent << "pid: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.pid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSEPL_WRAPPER_MN_MESSAGE_SIGNALSYNCREQUEST_H
