# link_match_minimum_response_fine: 0.4
# link_scan_maximum_distance: 20.0
# loop_search_maximum_distance: 50.0
# distance_variance_penalty: 1.8
# angle_variance_penalty: 0.20
# minimum_angle_penalty: 1.6 #0.9

# Plugin params
solver_plugin: solver_plugins::CeresSolver
ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
ceres_preconditioner: SCHUR_JACOBI
ceres_trust_strategy: LEVENBERG_MARQUARDT
ceres_dogleg_type: TRADITIONAL_DOGLEG
ceres_loss_function: None

# ROS Parameters
# odom_frame: odom
# map_frame: map
# map_name: /map
# base_frame: base_link
# scan_topic: /scan
mode: mapping #localization
debug_logging: false
throttle_scans: 1
transform_publish_period: 0.02 #if 0 never publishes odometry
# map_update_interval: 10.0
map_update_interval: 1.0
resolution: 0.05
max_laser_range: 3.5 #for rastering images
minimum_time_interval: 0.5
transform_timeout: 0.2
tf_buffer_duration: 14400.
stack_size_to_use: 40000000 #// program needs a larger stack size to serialize large maps
enable_interactive_mode: true

# General Parameters
use_scan_matching: true
use_scan_barycenter: true
minimum_travel_distance: 0.12
minimum_travel_heading: 0.174             #in radians
scan_buffer_size: 70
scan_buffer_maximum_scan_distance: 3.5
link_match_minimum_response_fine: 0.12
link_scan_maximum_distance: 3.5
loop_search_maximum_distance: 3.5
do_loop_closing: true
loop_match_minimum_chain_size: 10
loop_match_maximum_variance_coarse: 0.4   # gets squared later
loop_match_minimum_response_coarse: 0.8
loop_match_minimum_response_fine: 0.8

# Correlation Parameters - Correlation Parameters
correlation_search_space_dimension: 0.3
correlation_search_space_resolution: 0.01
correlation_search_space_smear_deviation: 0.03

# Correlation Parameters - Loop Closure Parameters
loop_search_space_dimension: 8.0
loop_search_space_resolution: 0.05
loop_search_space_smear_deviation: 0.03

# Scan Matcher Parameters
distance_variance_penalty: 0.3      # gets squared later
angle_variance_penalty: 0.349       # in degrees (gets converted to radians then squared)

fine_search_angle_offset: 0.00349   # in degrees (gets converted to radians)
coarse_search_angle_offset: 0.349   # in degrees (gets converted to radians)
coarse_angle_resolution: 0.0349     # in degrees (gets converted to radians)
minimum_angle_penalty: 0.9
minimum_distance_penalty: 0.5
use_response_expansion: false
