/* This file was autogenerated by openCONFIGURATOR-1.4.1 on 14-Apr-2020 11:23:42 */
#ifndef XAP_h
#define XAP_h

# define COMPUTED_PI_OUT_SIZE 76
typedef struct
{
	unsigned CN1_M01_vl_vl:16;
	unsigned CN1_M02_vr_vr:16;
	unsigned CN1_M03_sv_sv:16;
	unsigned CN1_M04_sw_sw:16;
	unsigned CN1_M05_svl_svl:16;
	unsigned CN1_M06_svr_svr:16;
	unsigned CN1_M07_ul_ul:16;
	unsigned CN1_M08_ur_ur:16;
	unsigned CN1_M11_Timestamp_L_Timestamp_L:32;
	unsigned CN1_M12_X_L_X_L:32;
	unsigned CN1_M13_Y_L_Y_L:32;
	unsigned CN1_M14_Z_L_Z_L:32;
	unsigned CN1_M15_Flags_L_Flags_L:8;
	unsigned CN1_M16_ID_L_ID_L:8;
	unsigned CN1_M17_Angle_L_Angle_L:16;
	unsigned CN1_M18_ETime_L_ETime_L:16;
	unsigned PADDING_VAR_1:16;
	unsigned CN1_M21_Timestamp_R_Timestamp_R:32;
	unsigned CN1_M22_X_R_X_R:32;
	unsigned CN1_M23_Y_R_Y_R:32;
	unsigned CN1_M24_Z_R_Z_R:32;
	unsigned CN1_M25_Flags_R_Flags_R:8;
	unsigned CN1_M26_ID_R_ID_R:8;
	unsigned CN1_M27_Angle_R_Angle_R:16;
	unsigned CN1_M28_ETime_R_ETime_R:16;
	unsigned CN1_M31_Actual_Filter_ID_L_Actual_Filter_ID_L:8;
	unsigned CN1_M32_Actual_Filter_ID_R_Actual_Filter_ID_R:8;
	unsigned CN1_M01_X_act_X_act:32;
	unsigned CN1_M02_Y_act_Y_act:32;
	unsigned CN1_M03_Angle_act_Angle_act:16;
	unsigned PADDING_VAR_2:16;
} PI_OUT;

# define COMPUTED_PI_IN_SIZE 36
typedef struct
{
	unsigned CN1_M01_vl_set_vl_set:16;
	unsigned CN1_M02_vr_set_vr_set:16;
	unsigned CN1_M03_mode_mode:8;
	unsigned CN1_M04_resets_resets:8;
	unsigned CN1_M05_kv_kv:16;
	unsigned CN1_M06_kw_kw:16;
	unsigned CN1_M07_kp_kp:16;
	unsigned CN1_M08_ki_ki:32;
	unsigned CN1_M09_tm_tm:16;
	unsigned CN1_M0A_t_t:16;
	unsigned CN1_M0B_s_gain_s_gain:16;
	unsigned CN1_M0C_F_ID_L_F_ID_L:8;
	unsigned CN1_M0D_F_ID_R_F_ID_R:8;
	unsigned CN1_M0E_angle_offset_angle_offset:16;
	unsigned PADDING_VAR_1:16;
	unsigned CN1_M0F_xs_xs:32;
	unsigned CN1_M10_ys_ys:32;
} PI_IN;

#endif
