(cl:in-package rosepl_wrapper_mn-msg)
(cl:export '(SHM_NAME-VAL
          SHM_NAME
          PID-VAL
          PID
          CN1_DIGITALOUTPUT_00H_AU8_DIGITALOUTPUT-VAL
          CN1_DIGITALOUTPUT_00H_AU8_DIGITALOUTPUT
          CN32_DIGITALOUTPUT_00H_AU8_DIGITALOUTPUT-VAL
          CN32_DIGITALOUTPUT_00H_AU8_DIGITALOUTPUT
          CN110_DIGITALOUTPUT_00H_AU8_DIGITALOUTPUT-VAL
          CN110_DIGITALOUTPUT_00H_AU8_DIGITALOUTPUT
))