(cl:in-package rosepl_wrapper_mn-msg)
(cl:export '(SHM_NAME-VAL
          SHM_NAME
          PID-VAL
          PID
          CN1_DIGITALINPUT_00H_AU8_DIGITALINPUT-VAL
          CN1_DIGITALINPUT_00H_AU8_DIGITALINPUT
          CN32_DIGITALINPUT_00H_AU8_DIGITALINPUT-VAL
          CN32_DIGITALINPUT_00H_AU8_DIGITALINPUT
          CN110_DIGITALINPUT_00H_AU8_DIGITALINPUT-VAL
          CN110_DIGITALINPUT_00H_AU8_DIGITALINPUT
))