// Generated by gencpp from file rosepl_wrapper_cn/PowerlinkIn.msg
// DO NOT EDIT!


#ifndef ROSEPL_WRAPPER_CN_MESSAGE_POWERLINKIN_H
#define ROSEPL_WRAPPER_CN_MESSAGE_POWERLINKIN_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rosepl_wrapper_cn
{
template <class ContainerAllocator>
struct PowerlinkIn_
{
  typedef PowerlinkIn_<ContainerAllocator> Type;

  PowerlinkIn_()
    : shm_name()
    , pid(0)
    , mm_x_pos(0)
    , mm_y_pos(0)
    , mm_z_pos(0)
    , mm_x_orient(0)
    , mm_y_orient(0)
    , mm_z_orient(0)
    , mm_w_orient(0)
    , odom_lwheel(0)
    , odom_rwheel(0)  {
    }
  PowerlinkIn_(const ContainerAllocator& _alloc)
    : shm_name(_alloc)
    , pid(0)
    , mm_x_pos(0)
    , mm_y_pos(0)
    , mm_z_pos(0)
    , mm_x_orient(0)
    , mm_y_orient(0)
    , mm_z_orient(0)
    , mm_w_orient(0)
    , odom_lwheel(0)
    , odom_rwheel(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _shm_name_type;
  _shm_name_type shm_name;

   typedef uint16_t _pid_type;
  _pid_type pid;

   typedef int64_t _mm_x_pos_type;
  _mm_x_pos_type mm_x_pos;

   typedef int64_t _mm_y_pos_type;
  _mm_y_pos_type mm_y_pos;

   typedef int64_t _mm_z_pos_type;
  _mm_z_pos_type mm_z_pos;

   typedef int64_t _mm_x_orient_type;
  _mm_x_orient_type mm_x_orient;

   typedef int64_t _mm_y_orient_type;
  _mm_y_orient_type mm_y_orient;

   typedef int64_t _mm_z_orient_type;
  _mm_z_orient_type mm_z_orient;

   typedef int64_t _mm_w_orient_type;
  _mm_w_orient_type mm_w_orient;

   typedef int64_t _odom_lwheel_type;
  _odom_lwheel_type odom_lwheel;

   typedef int64_t _odom_rwheel_type;
  _odom_rwheel_type odom_rwheel;





  typedef boost::shared_ptr< ::rosepl_wrapper_cn::PowerlinkIn_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosepl_wrapper_cn::PowerlinkIn_<ContainerAllocator> const> ConstPtr;

}; // struct PowerlinkIn_

typedef ::rosepl_wrapper_cn::PowerlinkIn_<std::allocator<void> > PowerlinkIn;

typedef boost::shared_ptr< ::rosepl_wrapper_cn::PowerlinkIn > PowerlinkInPtr;
typedef boost::shared_ptr< ::rosepl_wrapper_cn::PowerlinkIn const> PowerlinkInConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosepl_wrapper_cn::PowerlinkIn_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosepl_wrapper_cn::PowerlinkIn_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rosepl_wrapper_cn::PowerlinkIn_<ContainerAllocator1> & lhs, const ::rosepl_wrapper_cn::PowerlinkIn_<ContainerAllocator2> & rhs)
{
  return lhs.shm_name == rhs.shm_name &&
    lhs.pid == rhs.pid &&
    lhs.mm_x_pos == rhs.mm_x_pos &&
    lhs.mm_y_pos == rhs.mm_y_pos &&
    lhs.mm_z_pos == rhs.mm_z_pos &&
    lhs.mm_x_orient == rhs.mm_x_orient &&
    lhs.mm_y_orient == rhs.mm_y_orient &&
    lhs.mm_z_orient == rhs.mm_z_orient &&
    lhs.mm_w_orient == rhs.mm_w_orient &&
    lhs.odom_lwheel == rhs.odom_lwheel &&
    lhs.odom_rwheel == rhs.odom_rwheel;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rosepl_wrapper_cn::PowerlinkIn_<ContainerAllocator1> & lhs, const ::rosepl_wrapper_cn::PowerlinkIn_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rosepl_wrapper_cn

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rosepl_wrapper_cn::PowerlinkIn_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosepl_wrapper_cn::PowerlinkIn_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosepl_wrapper_cn::PowerlinkIn_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosepl_wrapper_cn::PowerlinkIn_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosepl_wrapper_cn::PowerlinkIn_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosepl_wrapper_cn::PowerlinkIn_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosepl_wrapper_cn::PowerlinkIn_<ContainerAllocator> >
{
  static const char* value()
  {
    return "43ef1fa8f235c243a4ab2c833daf73da";
  }

  static const char* value(const ::rosepl_wrapper_cn::PowerlinkIn_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x43ef1fa8f235c243ULL;
  static const uint64_t static_value2 = 0xa4ab2c833daf73daULL;
};

template<class ContainerAllocator>
struct DataType< ::rosepl_wrapper_cn::PowerlinkIn_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosepl_wrapper_cn/PowerlinkIn";
  }

  static const char* value(const ::rosepl_wrapper_cn::PowerlinkIn_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosepl_wrapper_cn::PowerlinkIn_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Generated with epl_ros_generator.py\n"
"\n"
"# openPOWERLINK variables:\n"
"string shm_name\n"
"uint16 pid\n"
"\n"
"# xap.h variables:\n"
"# uint8 DigitalOutput\n"
"int64 mm_x_pos\n"
"int64 mm_y_pos\n"
"int64 mm_z_pos\n"
"int64 mm_x_orient\n"
"int64 mm_y_orient\n"
"int64 mm_z_orient\n"
"int64 mm_w_orient\n"
"int64 odom_lwheel\n"
"int64 odom_rwheel\n"
;
  }

  static const char* value(const ::rosepl_wrapper_cn::PowerlinkIn_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosepl_wrapper_cn::PowerlinkIn_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.shm_name);
      stream.next(m.pid);
      stream.next(m.mm_x_pos);
      stream.next(m.mm_y_pos);
      stream.next(m.mm_z_pos);
      stream.next(m.mm_x_orient);
      stream.next(m.mm_y_orient);
      stream.next(m.mm_z_orient);
      stream.next(m.mm_w_orient);
      stream.next(m.odom_lwheel);
      stream.next(m.odom_rwheel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PowerlinkIn_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosepl_wrapper_cn::PowerlinkIn_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosepl_wrapper_cn::PowerlinkIn_<ContainerAllocator>& v)
  {
    s << indent << "shm_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.shm_name);
    s << indent << "pid: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.pid);
    s << indent << "mm_x_pos: ";
    Printer<int64_t>::stream(s, indent + "  ", v.mm_x_pos);
    s << indent << "mm_y_pos: ";
    Printer<int64_t>::stream(s, indent + "  ", v.mm_y_pos);
    s << indent << "mm_z_pos: ";
    Printer<int64_t>::stream(s, indent + "  ", v.mm_z_pos);
    s << indent << "mm_x_orient: ";
    Printer<int64_t>::stream(s, indent + "  ", v.mm_x_orient);
    s << indent << "mm_y_orient: ";
    Printer<int64_t>::stream(s, indent + "  ", v.mm_y_orient);
    s << indent << "mm_z_orient: ";
    Printer<int64_t>::stream(s, indent + "  ", v.mm_z_orient);
    s << indent << "mm_w_orient: ";
    Printer<int64_t>::stream(s, indent + "  ", v.mm_w_orient);
    s << indent << "odom_lwheel: ";
    Printer<int64_t>::stream(s, indent + "  ", v.odom_lwheel);
    s << indent << "odom_rwheel: ";
    Printer<int64_t>::stream(s, indent + "  ", v.odom_rwheel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSEPL_WRAPPER_CN_MESSAGE_POWERLINKIN_H
