// Generated by gencpp from file rosepl_wrapper_cn/SignalSyncResponse.msg
// DO NOT EDIT!


#ifndef ROSEPL_WRAPPER_CN_MESSAGE_SIGNALSYNCRESPONSE_H
#define ROSEPL_WRAPPER_CN_MESSAGE_SIGNALSYNCRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rosepl_wrapper_cn
{
template <class ContainerAllocator>
struct SignalSyncResponse_
{
  typedef SignalSyncResponse_<ContainerAllocator> Type;

  SignalSyncResponse_()
    : success(false)  {
    }
  SignalSyncResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::rosepl_wrapper_cn::SignalSyncResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosepl_wrapper_cn::SignalSyncResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SignalSyncResponse_

typedef ::rosepl_wrapper_cn::SignalSyncResponse_<std::allocator<void> > SignalSyncResponse;

typedef boost::shared_ptr< ::rosepl_wrapper_cn::SignalSyncResponse > SignalSyncResponsePtr;
typedef boost::shared_ptr< ::rosepl_wrapper_cn::SignalSyncResponse const> SignalSyncResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosepl_wrapper_cn::SignalSyncResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosepl_wrapper_cn::SignalSyncResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rosepl_wrapper_cn::SignalSyncResponse_<ContainerAllocator1> & lhs, const ::rosepl_wrapper_cn::SignalSyncResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rosepl_wrapper_cn::SignalSyncResponse_<ContainerAllocator1> & lhs, const ::rosepl_wrapper_cn::SignalSyncResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rosepl_wrapper_cn

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rosepl_wrapper_cn::SignalSyncResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosepl_wrapper_cn::SignalSyncResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosepl_wrapper_cn::SignalSyncResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosepl_wrapper_cn::SignalSyncResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosepl_wrapper_cn::SignalSyncResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosepl_wrapper_cn::SignalSyncResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosepl_wrapper_cn::SignalSyncResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::rosepl_wrapper_cn::SignalSyncResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::rosepl_wrapper_cn::SignalSyncResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosepl_wrapper_cn/SignalSyncResponse";
  }

  static const char* value(const ::rosepl_wrapper_cn::SignalSyncResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosepl_wrapper_cn::SignalSyncResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"\n"
;
  }

  static const char* value(const ::rosepl_wrapper_cn::SignalSyncResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosepl_wrapper_cn::SignalSyncResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SignalSyncResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosepl_wrapper_cn::SignalSyncResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosepl_wrapper_cn::SignalSyncResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSEPL_WRAPPER_CN_MESSAGE_SIGNALSYNCRESPONSE_H
