// Generated by gencpp from file rosepl_wrapper_cn/SignalSync.msg
// DO NOT EDIT!


#ifndef ROSEPL_WRAPPER_CN_MESSAGE_SIGNALSYNC_H
#define ROSEPL_WRAPPER_CN_MESSAGE_SIGNALSYNC_H

#include <ros/service_traits.h>


#include <rosepl_wrapper_cn/SignalSyncRequest.h>
#include <rosepl_wrapper_cn/SignalSyncResponse.h>


namespace rosepl_wrapper_cn
{

struct SignalSync
{

typedef SignalSyncRequest Request;
typedef SignalSyncResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SignalSync
} // namespace rosepl_wrapper_cn


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rosepl_wrapper_cn::SignalSync > {
  static const char* value()
  {
    return "242caa9d447108ca38b61cc3364649f4";
  }

  static const char* value(const ::rosepl_wrapper_cn::SignalSync&) { return value(); }
};

template<>
struct DataType< ::rosepl_wrapper_cn::SignalSync > {
  static const char* value()
  {
    return "rosepl_wrapper_cn/SignalSync";
  }

  static const char* value(const ::rosepl_wrapper_cn::SignalSync&) { return value(); }
};


// service_traits::MD5Sum< ::rosepl_wrapper_cn::SignalSyncRequest> should match
// service_traits::MD5Sum< ::rosepl_wrapper_cn::SignalSync >
template<>
struct MD5Sum< ::rosepl_wrapper_cn::SignalSyncRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rosepl_wrapper_cn::SignalSync >::value();
  }
  static const char* value(const ::rosepl_wrapper_cn::SignalSyncRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosepl_wrapper_cn::SignalSyncRequest> should match
// service_traits::DataType< ::rosepl_wrapper_cn::SignalSync >
template<>
struct DataType< ::rosepl_wrapper_cn::SignalSyncRequest>
{
  static const char* value()
  {
    return DataType< ::rosepl_wrapper_cn::SignalSync >::value();
  }
  static const char* value(const ::rosepl_wrapper_cn::SignalSyncRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rosepl_wrapper_cn::SignalSyncResponse> should match
// service_traits::MD5Sum< ::rosepl_wrapper_cn::SignalSync >
template<>
struct MD5Sum< ::rosepl_wrapper_cn::SignalSyncResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rosepl_wrapper_cn::SignalSync >::value();
  }
  static const char* value(const ::rosepl_wrapper_cn::SignalSyncResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosepl_wrapper_cn::SignalSyncResponse> should match
// service_traits::DataType< ::rosepl_wrapper_cn::SignalSync >
template<>
struct DataType< ::rosepl_wrapper_cn::SignalSyncResponse>
{
  static const char* value()
  {
    return DataType< ::rosepl_wrapper_cn::SignalSync >::value();
  }
  static const char* value(const ::rosepl_wrapper_cn::SignalSyncResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSEPL_WRAPPER_CN_MESSAGE_SIGNALSYNC_H
