using System;
using System.Runtime.InteropServices;

/// <summary>
/// This file was autogenerated by openCONFIGURATOR-2.2.1_release on 13-May-2020 00:04:55
/// Project: epl4
/// Application process for MN(240)
/// </summary>

namespace openPOWERLINK
{

	/// <summary>
	/// Struct : ProcessImage Out
	/// </summary>
	[StructLayout(LayoutKind.Explicit, Pack = 1, Size = 72)]
	public struct AppProcessImageOut
	{
		[FieldOffset(0)]
		public Int64 CN1_mm_x_pos1;
		[FieldOffset(8)]
		public Int64 CN1_mm_y_pos2;
		[FieldOffset(16)]
		public Int64 CN1_mm_z_pos3;
		[FieldOffset(24)]
		public Int64 CN1_mm_x_orient4;
		[FieldOffset(32)]
		public Int64 CN1_mm_y_orient5;
		[FieldOffset(40)]
		public Int64 CN1_mm_z_orient6;
		[FieldOffset(48)]
		public Int64 CN1_mm_w_orient7;
		[FieldOffset(56)]
		public Int64 CN1_odom_lwheel14;
		[FieldOffset(64)]
		public Int64 CN1_odom_rwheel15;
	}

	/// <summary>
	/// Struct : ProcessImage In
	/// </summary>
	[StructLayout(LayoutKind.Explicit, Pack = 1, Size = 16)]
	public struct AppProcessImageIn
	{
		[FieldOffset(0)]
		public Int64 CN1_cmdvel_lwheel1;
		[FieldOffset(8)]
		public Int64 CN1_cmdvel_rwheel2;
	}

}
