(cl:defpackage rosepl_wrapper_cn-srv
  (:use )
  (:export
   "SDOTRANSFER"
   "<SDOTRANSFER-REQUEST>"
   "SDOTRANSFER-REQUEST"
   "<SDOTRANSFER-RESPONSE>"
   "SDOTRANSFER-RESPONSE"
   "SIGNALSYNC"
   "<SIGNALSYNC-REQUEST>"
   "SIGNALSYNC-REQUEST"
   "<SIGNALSYNC-RESPONSE>"
   "SIGNALSYNC-RESPONSE"
  ))

