/* This file was autogenerated by openCONFIGURATOR-1.4.1 on 26-Apr-2020 12:37:43 */
#ifndef XAP_h
#define XAP_h

#define COEF_FLOAT_POINT 10000

# define COMPUTED_PI_OUT_SIZE 16
typedef struct
{
	int64_t CN1_M0A_cmdvel_lwheel1;
	int64_t CN1_M0B_cmdvel_rwheel2;
} PI_OUT;

# define COMPUTED_PI_IN_SIZE 72
typedef struct
{
	int64_t CN1_M01_mm_x_pos1;
	int64_t CN1_M02_mm_y_pos2;
	int64_t CN1_M03_mm_z_pos3;
	int64_t CN1_M04_mm_x_orient4;
	int64_t CN1_M05_mm_y_orient5;
	int64_t CN1_M06_mm_z_orient6;
	int64_t CN1_M07_mm_w_orient7;
	int64_t CN1_M08_odom_lwheel8;
	int64_t CN1_M09_odom_rwheel9;
} PI_IN;

#endif
