using System;
using System.Runtime.InteropServices;
/// <summary>
/// This file was autogenerated by openCONFIGURATOR-1.4.1 on 14-Apr-2020 11:23:42
/// </summary>

namespace openPOWERLINK
{

	/// <summary>
	/// Struct : ProcessImage Out
	/// </summary>
	[StructLayout(LayoutKind.Explicit, Pack = 1, Size = 76)]
	public struct AppProcessImageOut
	{
		[FieldOffset(0)]
		public Int16 CN1_M01_vl_vl;
		[FieldOffset(2)]
		public Int16 CN1_M02_vr_vr;
		[FieldOffset(4)]
		public Int16 CN1_M03_sv_sv;
		[FieldOffset(6)]
		public Int16 CN1_M04_sw_sw;
		[FieldOffset(8)]
		public Int16 CN1_M05_svl_svl;
		[FieldOffset(10)]
		public Int16 CN1_M06_svr_svr;
		[FieldOffset(12)]
		public Int16 CN1_M07_ul_ul;
		[FieldOffset(14)]
		public Int16 CN1_M08_ur_ur;
		[FieldOffset(16)]
		public UInt32 CN1_M11_Timestamp_L_Timestamp_L;
		[FieldOffset(20)]
		public Int32 CN1_M12_X_L_X_L;
		[FieldOffset(24)]
		public Int32 CN1_M13_Y_L_Y_L;
		[FieldOffset(28)]
		public Int32 CN1_M14_Z_L_Z_L;
		[FieldOffset(32)]
		public byte CN1_M15_Flags_L_Flags_L;
		[FieldOffset(33)]
		public byte CN1_M16_ID_L_ID_L;
		[FieldOffset(34)]
		public UInt16 CN1_M17_Angle_L_Angle_L;
		[FieldOffset(36)]
		public UInt16 CN1_M18_ETime_L_ETime_L;
		[FieldOffset(38)]
		public byte PADDING_VAR_1;
		[FieldOffset(39)]
		public byte PADDING_VAR_2;
		[FieldOffset(40)]
		public UInt32 CN1_M21_Timestamp_R_Timestamp_R;
		[FieldOffset(44)]
		public Int32 CN1_M22_X_R_X_R;
		[FieldOffset(48)]
		public Int32 CN1_M23_Y_R_Y_R;
		[FieldOffset(52)]
		public Int32 CN1_M24_Z_R_Z_R;
		[FieldOffset(56)]
		public byte CN1_M25_Flags_R_Flags_R;
		[FieldOffset(57)]
		public byte CN1_M26_ID_R_ID_R;
		[FieldOffset(58)]
		public UInt16 CN1_M27_Angle_R_Angle_R;
		[FieldOffset(60)]
		public UInt16 CN1_M28_ETime_R_ETime_R;
		[FieldOffset(62)]
		public byte CN1_M31_Actual_Filter_ID_L_Actual_Filter_ID_L;
		[FieldOffset(63)]
		public byte CN1_M32_Actual_Filter_ID_R_Actual_Filter_ID_R;
		[FieldOffset(64)]
		public Int32 CN1_M01_X_act_X_act;
		[FieldOffset(68)]
		public Int32 CN1_M02_Y_act_Y_act;
		[FieldOffset(72)]
		public Int16 CN1_M03_Angle_act_Angle_act;
		[FieldOffset(74)]
		public byte PADDING_VAR_3;
		[FieldOffset(75)]
		public byte PADDING_VAR_4;
	}

	/// <summary>
	/// Struct : ProcessImage In
	/// </summary>
	[StructLayout(LayoutKind.Explicit, Pack = 1, Size = 36)]
	public struct AppProcessImageIn
	{
		[FieldOffset(0)]
		public Int16 CN1_M01_vl_set_vl_set;
		[FieldOffset(2)]
		public Int16 CN1_M02_vr_set_vr_set;
		[FieldOffset(4)]
		public byte CN1_M03_mode_mode;
		[FieldOffset(5)]
		public byte CN1_M04_resets_resets;
		[FieldOffset(6)]
		public Int16 CN1_M05_kv_kv;
		[FieldOffset(8)]
		public Int16 CN1_M06_kw_kw;
		[FieldOffset(10)]
		public Int16 CN1_M07_kp_kp;
		[FieldOffset(12)]
		public Int32 CN1_M08_ki_ki;
		[FieldOffset(16)]
		public UInt16 CN1_M09_tm_tm;
		[FieldOffset(18)]
		public UInt16 CN1_M0A_t_t;
		[FieldOffset(20)]
		public Int16 CN1_M0B_s_gain_s_gain;
		[FieldOffset(22)]
		public byte CN1_M0C_F_ID_L_F_ID_L;
		[FieldOffset(23)]
		public byte CN1_M0D_F_ID_R_F_ID_R;
		[FieldOffset(24)]
		public Int16 CN1_M0E_angle_offset_angle_offset;
		[FieldOffset(26)]
		public byte PADDING_VAR_1;
		[FieldOffset(27)]
		public byte PADDING_VAR_2;
		[FieldOffset(28)]
		public Int32 CN1_M0F_xs_xs;
		[FieldOffset(32)]
		public Int32 CN1_M10_ys_ys;
	}
}
