/* This file was autogenerated by openCONFIGURATOR-1.4.1 on 26-Apr-2020 12:37:43 */
#ifndef XAP_h
#define XAP_h

#define COEF_FLOAT_POINT 10000

# define COMPUTED_PI_OUT_SIZE 72
typedef struct
{
	unsigned mm_x_pos:64;
	unsigned mm_y_pos:64;
	unsigned mm_z_pos:64;
	unsigned mm_x_orient:64;
	unsigned mm_y_orient:64;
	unsigned mm_z_orient:64;
	unsigned mm_w_orient:64;
	unsigned odom_lwheel:64;
	unsigned odom_rwheel:64;
} PI_OUT;

# define COMPUTED_PI_IN_SIZE 16
typedef struct
{
	unsigned cmdvel_lwheel:64;
	unsigned cmdvel_rwheel:64;
} PI_IN;

#endif
